version: 2.1
jobs:
  build:
    docker:
     - image: circleci/node:13.8.0
    steps:
      - checkout
      - run: npm 1
      - run: npm run lint 

  test:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - checkout
      - run: npm run test 
  analyz: 
    docker:
      - image: circleci/node:13.8.0
    steps:
      - checkout
      - run: npm run audit       
workflows:
  jobs:
  - build
  - test:
      requires:
        - build
  - analyze:
      requires:
        - test 
